### PR TITLE
fix: Avoid panic for unanchorable/non-UTF8 git paths

### LINKED ISSUE #10403: `crates/turborepo-scm/src/git.rs` panics in GitHub Actions
### Verify canary release

- [x] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

TBD

### Which canary version will you have in your reproduction?

TBD

### Environment information

```block
CLI:
   Version: 2.5.2
   Path to executable: /Users/scarletflash/Projects/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/node_modules/.pnpm/turbo-darwin-arm64@2.5.2/node_modules/turbo-darwin-arm64/bin/turbo
   Daemon status: Running
   Package manager: pnpm9

Platform:
   Architecture: aarch64
   Operating system: macos
   WSL: false
   Available memory (MB): 97950
   Available CPU cores: 16

Environment:
   CI: None
   Terminal (TERM): xterm-256color
   Terminal program (TERM_PROGRAM): zed
   Terminal program version (TERM_PROGRAM_VERSION): 0.183.11
   Shell (SHELL): /bin/zsh
   stdin: false
```

### Expected behavior

```bash
turbo --color --no-update-notifier run --continue\=dependencies-successful --env-mode\=strict --log-order\=stream --cache-dir\=./.turbo --concurrency\=75% --affected _check-all
```

Is successfully executed in GitHub Action

### Actual behavior

GitHub Action fails with these logs:

```
> Run pnpm run check-all-affected
  
> ⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎@0.0.0 check-all-affected /home/runner/_work/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎
> pnpm run turbo-run --affected _check-all
> ⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎@0.0.0 turbo-run /home/runner/_work/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎
> pnpm run turbo run --continue=dependencies-successful --env-mode=strict --log-order=stream --cache-dir=./.turbo --concurrency=[7](https://github.com/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/actions/runs/14728347255/job/41336330595?pr=5174#step:9:7)5% --affected _check-all
> ⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎@0.0.0 turbo /home/runner/_work/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎
> turbo --color --no-update-notifier run --continue\=dependencies-successful --env-mode\=strict --log-order\=stream --cache-dir\=./.turbo --concurrency\=75% --affected _check-all
Oops! Turbo has crashed.
Caused by 
"name" = "turbo"
"operating_system" = "Ubuntu 22.4.0 (jammy) [64-bit]"
"crate_version" = "2.5.2"
"explanation" = """
file 'crates/turborepo-scm/src/git.rs' at line 359
"""
"cause" = '''
panicked at crates/turborepo-scm/src/git.rs:359:1[8](https://github.com/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/actions/runs/14728347255/job/41336330595?pr=5174#step:9:9):
called `Result::unwrap()` on an `Err` value: Path(NotParent("/home/runner/_work/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎", "/home/runner/_work/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/\"⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/packages/utilities/src/functions/get-all-prototypes.function\\321\\216.spec.ts\""), <disabled>)'''
"method" = "Panic"
"backtrace" = """
   0: 0x7ffaa5[9](https://github.com/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/actions/runs/14728347255/job/41336330595?pr=5174#step:9:10)358d5 - <unresolved>
   1: 0x7ffaa542ee36 - <unresolved>
   2: 0x7ffaa5132734 - <unresolved>
   3: 0x7ffaa55d97bb - <unresolved>
   4: 0x7ffaa4f3473d - <unresolved>
   5: 0x7ffaa51b04ce - <unresolved>
   6: 0x7ffaa51aab78 - <unresolved>
   7: 0x7ffaa529bfc0 - <unresolved>
   8: 0x7ffaa52ba42c - <unresolved>
   9: 0x7ffaa4eb5641 - <unresolved>
  10: 0x7ffaa4eae88e - <unresolved>
  11: 0x7ffaa55c8bf0 - <unresolved>
  [12](https://github.com/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/actions/runs/14728347255/job/41336330595?pr=5174#step:9:13): 0x7ffaa55c547b - <unresolved>
  13: 0x7ffaa41f6f5a - <unresolved>
  14: 0x7ffaa41f4c[13](https://github.com/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎/actions/runs/14728347255/job/41336330595?pr=5174#step:9:14) - <unresolved>
  15: 0x7ffaa41f7545 - <unresolved>"""
Please open an issue at https://github.com/vercel/turborepo/issues/new/choose and include this message in your issue
 ELIFECYCLE  Command failed with exit code 101.
 ELIFECYCLE  Command failed with exit code 101.
 ELIFECYCLE  Command failed with exit code 101.
Error: Process completed with exit code 101.
```

### To Reproduce

⚠️ **_Not verified yet_**

1. Prepare a TypeScript codebase with valid turbo tasks.
2. Configure GitHub Actions to check the codebase with the `--affected` flag.
3. Push a file with a corrupted file name into a repo (Cyrillic symbols in my case) and run the checks.
4. Observe the failed attempt to run.
5. Try cleaning the GitHub caches / deleting the corrupted file / renaming it
6. Observe the failed attempt to run again.
7. Remove the `--affected` flag.
8. Observe successful runs.

### Additional context

I'm sorry for the incomplete report ― I'll try to finalize it ASAP.
Removing the `--affected` flag helped run the CI, but now it's much slower.

Partial `package.json` to make it clear how we run commands:

```json
{
  "name": "⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎⬛︎",
  "scripts": {
    "check-all-affected": "pnpm run turbo-run --affected _check-all",
    "turbo": "turbo --color --no-update-notifier",
    "turbo-run": "pnpm run turbo run --continue=dependencies-successful --env-mode=strict --log-order=stream --cache-dir=./.turbo --concurrency=75%"
  },
  "engines": {
    "pnpm": "10.10.0",
    "node": "22.15.0"
  },
  "packageManager": "pnpm@10.10.0"
}
```

### PR DESCRIPTION
**Pull request by biru-codeastromer**
### What

Prevent a runtime panic in `crates/turborepo-scm/src/git.rs` when git emits paths that cannot be anchored to the turbo root (e.g. corrupted filenames, non-parent paths) or when git stdout contains non-UTF8 bytes. Instead of `unwrap()` → crash, errors propagate through the existing `Result` chain and the change detector falls back to treating all packages as changed.

### Why

GitHub Actions CI was failing for repositories that contain unusual filenames (Cyrillic / corrupted / non-UTF8). The panic originated in `add_files_from_stdout`'s `.unwrap()` calls and caused `--affected` CI runs to crash.

### How

**`crates/turborepo-scm/src/git.rs`**
- `add_files_from_stdout` now returns `Result<(), Error>` — replaced `.unwrap()` on `RelativeUnixPath::new()` and `reanchor_path_from_git_root_to_turbo_root()` with `?` propagation
- All 3 call sites in `changed_files` updated to propagate with `?`

**`crates/turborepo-scope/src/change_detector.rs`**
- Replaced `process::exit(1)` + `eprintln!` with a fail-safe fallback: on any SCM error, log via `tracing::warn!` and return all packages as changed (same pattern as the existing `InvalidRange` handler)
- Removed `std::process` and `Error as ScmError` imports — the library crate no longer terminates the process or couples to specific SCM error variant internals

**`crates/turborepo-repository/src/change_mapper/mod.rs`**
- Added `AllPackageChangeReason::ScmError { error: String }` variant for downstream consumers to understand why all packages were selected

**`crates/turborepo-query/src/lib.rs` + `affected_tasks.rs`**
- Added match arms for the new `ScmError` variant in the GraphQL query layer

### Behavior

When git emits unprocessable paths, instead of panicking:
1. The error propagates from `add_files_from_stdout` through `changed_files` to `changed_packages`
2. `changed_packages` catches it, logs a warning via `tracing::warn!`, and conservatively treats all packages as changed
3. CI runs everything rather than crashing — run summaries, telemetry, and TUI teardown all execute normally

Fix #10403

### CODE REVIEW

**Comment by biru-codeastromer** [comment]
Thanks  good call. I updated the change detector so SCM path errors now produce a hard failure (exit 1) with a focused, actionable error message on stderr instead of logging a warning and defaulting to “all packages changed”. This makes the failure visible in CI logs and avoids accidentally running full CI due to a stray problematic filename.

File: crates/turborepo-lib/src/run/scope/change_detector.rs [hunk 1]
```diff
@@ -116,17 +142,33 @@ impl<'a> GitChangeDetector for ScopeChangeDetector<'a> {
                     })
                     .collect());
             }
-            Ok(changed_files) => changed_files,
+            Err(ScmError::Path(err, _)) => {
+                // Hard fail: path anchoring errors should be visible in CI logs.
```
Comment (anthonyshew) [inline crates/turborepo-lib/src/run/scope/change_detector.rs]:
```suggestion
```

File: crates/turborepo-lib/src/run/scope/change_detector.rs [hunk 2]
```diff
@@ -116,17 +142,33 @@ impl<'a> GitChangeDetector for ScopeChangeDetector<'a> {
...
+                    "error: failed to process file paths from SCM: {}.\nThis repository has file \
+                     paths that could not be anchored to the turbo root.\nPlease remove/rename \
+                     the problematic file(s) or fix repository layout and try again.",
+                    err
+                );
+                process::exit(1);
+            }
+            Err(err) => {
+                // Any other SCM error should also fail hard so users see a clear error instead
+                // of a silent fallback that runs full CI.
```
Comment (anthonyshew) [inline crates/turborepo-lib/src/run/scope/change_detector.rs]:
```suggestion
```

File: crates/turborepo-lib/src/run/scope/change_detector.rs [hunk 3]
```diff
@@ -116,17 +142,33 @@ impl<'a> GitChangeDetector for ScopeChangeDetector<'a> {
...
+                eprintln!(
+                    "error: unexpected SCM error while detecting changed files: {}.\nAborting to \
+                     avoid running all CI tasks silently. See the error above for details.",
```
Comment (anthonyshew) [inline crates/turborepo-lib/src/run/scope/change_detector.rs]:
```suggestion
                    "error: unexpected SCM error while detecting changed files: {}.\n
```

**Review by anthonyshew — COMMENTED** [review]
Please read and correct Claude's output before submitting it in a pull request. If you are not able to verify the completeness of the provided implementation because you do not understand it, please do not send a pull request.

The Vercel review is correct. You need to update the PR description.

Additionally, lets add some unit testing in accordance with this fix. Sorry for not mentioning this earlier.

**Comment by biru-codeastromer** [comment]
I will be adding the unit test soon
