### PR TITLE
git integration cleanup

### LINKED ISSUE #1157: --filter=[HEAD^1] works but --filter=[HEAD^N] returns error
### What version of Turborepo are you using?

1.1.5

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

`npx turbo run test --filter='[HEAD^1]' --dry=json | jq '.packages'` works but going past HEAD^1 always returns an error.

```
npx turbo run test --filter='[HEAD^2]' --dry=json | jq '.packages'
unable to check diff vs. HEAD^2: exit status 128
```

If i choose a particular commit in the past that works...

`npx turbo run test --filter='[b2cbc9dd2]' --dry=json | jq '.packages'`

### Expected Behavior

Support HEAD^N references to filter.

### To Reproduce

1. clone any repo w/ turbo support (including this repo)
2. run a dry run with a filter using HEAD^5

### PR DESCRIPTION
**Pull request by gsoltis**
* Delete a lot of unused git integration code
 * Don't crash in git integration code, return an error instead (remove `log.Fatalf` instances)
 * Provide a more helpful error message when the user supplies a non-existent commit

Fixes #1157

### CODE REVIEW

**Review by jaredpalmer — APPROVED** [review]

File: cli/internal/scope/scope.go [hunk 1]
```diff
@@ -92,9 +92,13 @@ func (o *Opts) getPackageChangeFunc(scm scm.SCM, packageInfos map[interface{}]*f
 		// that the changes we're interested in are scoped, but we need to handle
 		// global dependencies changing as well. A future optimization might be to
 		// scope changed files more deeply if we know there are no global dependencies.
-		changedFiles := []string{}
+		var changedFiles []string
```
Comment (nathanhammond) [inline cli/internal/scope/scope.go:95]: This made me learn that `range` over a `nil` slice is totally fine.

**Review by nathanhammond — COMMENTED** [review]
```diff
+ 52
- 183
```

And lots of things no longer exported. 🎉
