### PR TITLE
fix(watch): allow usage of turbo.jsonc

### LINKED ISSUE #10323: Watch mode doesn't work inside a project with nested turbo.jsonc
### Verify canary release

- [x] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/neochief/bug-turborepo-jsonc

### Which canary version will you have in your reproduction?

2.5.1-canary.0

### Expected behavior

I created turbo.jsonc at the project root, and everything was fine. As soon as I extended it in the subpackage, the watch mode stopped working.

### Actual behavior

```
> turbo watch build                                                                                                               
turbo 2.5.1-canary.0

  × Cannot use root turbo.json at /Users/neochief/www/testtest/turbo.jsonc with Watch Mode.

```

### To Reproduce

1. Create a root turbo.jsonc.
2. Create an extending turbo.jsonc in a subpackage.

### PR DESCRIPTION
**Pull request by anthonyshew**
### Description

Fixes #10323

### Testing Instructions

I'm testing by hand as I'm aware its notoriously difficult to write tests in this area of the codebase.

### CODE REVIEW

File: crates/turborepo-lib/src/run/watch.rs [hunk 1]
```diff
@@ -120,9 +120,14 @@ impl WatchClient {
...
-        // Check if the turbo.json path is the standard one
-        let standard_path = base.repo_root.join_component(CONFIG_FILE);
-        if base.opts.repo_opts.root_turbo_json_path != standard_path {
+        // Check if the turbo.json path is the standard one (either turbo.json or
+        // turbo.jsonc)
+        let standard_path_json = base.repo_root.join_component(CONFIG_FILE);
+        let standard_path_jsonc = base.repo_root.join_component(CONFIG_FILE_JSONC);
+
+        if base.opts.repo_opts.root_turbo_json_path != standard_path_json
+            && base.opts.repo_opts.root_turbo_json_path != standard_path_jsonc
```
Comment (anthonyshew) [inline crates/turborepo-lib/src/run/watch.rs:129]: I haven't been in any of the code for `watch` and have little context so not sure if this is an okay way to go about it. I just did the first, most minimally naive thing I saw.

**Review by chris-olszewski — CHANGES_REQUESTED** [review]
This will avoid the error, but we need to implement the correct behavior so that `turbo.jsonc` triggers a package watcher event.

**Comment by anthonyshew** [comment]
@chris-olszewski 🤦 When I hand-tested it, I was using a Just-in-Time package, so of course it looked like it worked.

I added some code that for filewatching (I hope) and used a Compiled Package now and hand-tested again. It looks like it works (for real this time) - but I only tested a simple case. Do I look like I'm more on the right track now?

File: crates/turborepo-lib/src/package_changes_watcher.rs [hunk 2]
```diff
@@ -426,17 +479,24 @@ impl Subscriber {
             }
         };
 
+        // Create a separate task for handling the exit signal
+        let exit_signal = tokio::spawn(async move {
+            let _ = exit_rx.await;
+            tracing::debug!("exiting package changes watcher due to signal");
+            true
+        });
```
Comment (chris-olszewski) [inline crates/turborepo-lib/src/package_changes_watcher.rs:487]: Guessing this was cursor, but please undo this change, the previous signal handling is the behavior we want.

File: crates/turborepo-lib/src/package_changes_watcher.rs [hunk 3]
```diff
@@ -171,9 +171,29 @@ impl Subscriber {
...
+                tracing::warn!(
+                    "Found both turbo.json and turbo.jsonc in {}. Using turbo.json for watching.",
+                    self.repo_root
+                );
+                turbo_json_path
+            }
+            (true, false) => turbo_json_path,
+            (false, true) => turbo_jsonc_path,
+            (false, false) => turbo_json_path, // Default to turbo.json if neither exists
+        };
```
Comment (chris-olszewski) [inline crates/turborepo-lib/src/package_changes_watcher.rs:192]: Not blocking, but would love to dedupe this logic with `Config::root_turbo_json_path` instead of copy-pasta. Would need to break out the behavior to a new static function.

**Review by chris-olszewski — APPROVED** [review]
LGTM, only thing that really needs to get changed is the change to the exit handling in the package watcher

File: crates/turborepo-lib/src/package_changes_watcher.rs (hunk 2 above)
Comment (anthonyshew) [reply crates/turborepo-lib/src/package_changes_watcher.rs]: Caught me red-handed.
