### PR TITLE
fix: Load custom CA certificates in fast webpki-only HTTP client

### LINKED ISSUE #12590: Turbo > 2.8.14 fails to connect to self-hosted remote cache server with custom CA
### Verify canary release

- [x] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/Jualex/turbo-ca-issue

### Which canary version will you have in your reproduction?

2.9.6-canary.2

### Environment information

```block
• turbo 2.9.6-canary.2
CLI:
   Version: 2.9.6-canary.2
   Path to executable: /Users/floegelj/Projects/TNG/bugreport/turbo/node_modules/@turbo/darwin-arm64/bin/turbo
   Daemon status: Not running
   Package manager: npm

Platform:
   Architecture: aarch64
   Operating system: macos
   WSL: false
   Available memory (MB): 26935
   Available CPU cores: 18

Environment:
   CI: None
   AI agent: None
   Terminal (TERM): xterm-256color
   Terminal program (TERM_PROGRAM): unknown
   Terminal program version (TERM_PROGRAM_VERSION): unknown
   Shell (SHELL): /bin/zsh
   stdin: false
   Node.js version: v24.14.1
```

### Expected behavior

The self-hosted remote cache (ducktors/turborepo-remote-cache) with a custom CA can be reached by turbo.

### Actual behavior

Turbo often fails to connect to the remote cache:

• turbo 2.9.6-canary.2

   • Running build
 WARNING     • Remote caching unavailable (Could not connect to "https://my-hostname:3000/")

build: cache miss, executing 5f1d1c4948da45c3
build:
build:
build: > test-package@0.0.1 build
build: > md5sum date.txt > date.md5
build:

 Tasks:    1 successful, 1 total
Cached:    0 cached, 1 total
  Time:    149ms

>   ...Finishing writing to cache...                                                                                                           WARNING  could not connect to the cache

### To Reproduce

* Check out the linked repository
* Run ./setup-ca.sh
* Run ./run-remote-cache.sh
* Add your $(hostname) to /etc/hosts to resolve to 127.0.0.1
* Run ./run.sh and cancel after seeing the error as the loop won't terminate

### Additional context

The given test setup was working with turbo versions up to 2.8.14. The error appears in all versions greater than that. We assume that this is related to the refactoring in the ApiClient that introduced the fast client.

The run.sh script contains a loop because the error does not happen with every request. There is just a high likelihood of the error happening.

Some observations: 
The likelihood increases by adding additional certificates to the CA file referenced in SSL_CERT_FILE.
The likelihood decreases if the .git directory is deleted.

Platforms:
We have observed the same bahavior on different Linux distros on amd64 (addtional to macOS on arm64).

### PR DESCRIPTION
**Pull request by anthonyshew**
## Summary

Closes #12590

- The two-phase `SharedHttpClient` builds a fast webpki-only client (~0ms) before the full native-certs client (~200ms on macOS). When a remote cache request fires before the native client is ready, the fast client handles it — but it has no custom CA certificates, so connections to self-hosted caches with custom CAs fail intermittently.
- The fast client now loads certificates from `SSL_CERT_FILE` and `SSL_CERT_DIR` env vars via file I/O (no Keychain access), preserving the performance benefit while ensuring custom CAs work from the first request.

### CODE REVIEW

File: crates/turborepo-api-client/src/lib.rs [hunk 1]
```diff
@@ -646,6 +646,14 @@ impl APIClient {
                 builder = builder
                     .tls_built_in_webpki_certs(true)
                     .tls_built_in_native_certs(use_native);
+                // When native certs are disabled (webpki-only fast path),
+                // manually load certificates from SSL_CERT_FILE / SSL_CERT_DIR
+                // so that custom CAs (e.g. corporate proxies, self-hosted
+                // caches) work even before the full native client is ready.
+                // This is pure file I/O — no macOS Keychain — so it stays fast.
```
Comment (anthonyshew) [inline crates/turborepo-api-client/src/lib.rs]:
```suggestion
```
