### PR TITLE
Prevent side effects when looking for config files.

### LINKED ISSUE #1270: Error while reading user config file
### What version of Turborepo are you using?

1.2.7

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

After updating `turbo` from 1.2.6 to 1.2.7, turbo crashes when it is launched. I run it in a node v16 container on self hosted GitHub Actions runner. When ran locally (on my MBP), it runs as expected.

```
$ turbo run test
 ERROR  reading user config file: could not create any of the following paths: /.config/turborepo, /etc/xdg/turborepo
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It seems that #1156 introduces the issue.

### Expected Behavior

`turbo` should not crash on startup if it is unable to read the user config file.

### To Reproduce

I'm not sure what to provide here…

### PR DESCRIPTION
**Pull request by nathanhammond**
As noted in https://github.com/vercel/turborepo/pull/1156#discussion_r863341102, `xdg.ConfigFile` has side effects. One of the consequences of the side effects is that sometimes, when simply wanting to check for existence, we would error out entirely because the path wasn't writable.

This splits the process of creating and reading a config file path, which means that the error won't be encountered unless a user is explicitly trying to create a configuration file. (Which *should* be an error.)

Fixes #1270

### CODE REVIEW

File: cli/internal/config/config_file_test.go [hunk 1]
```diff
@@ -102,7 +147,7 @@ func TestReadUserConfigWhenMissing(t *testing.T) {
 }
 
 func TestWriteUserConfig(t *testing.T) {
-	fsys := afero.NewMemMapFs()
+	fsys := afero.NewOsFs()
```
Comment (nathanhammond) [inline cli/internal/config/config_file_test.go:150]: We, unfortunately, need to rip `afero` out.

XDG also only checks the OS file system, so it is pretty much nonsense to use an `afero` `MemMapFs` here.

Comment (gsoltis) [reply cli/internal/config/config_file_test.go:150]: Yeah. Would've been nice.

File: cli/internal/config/config_file_test.go [hunk 2]
```diff
@@ -9,6 +9,51 @@ import (
...
+			// XDG is not filesystem aware. Clean up first.
+			path, _ := createUserConfigPath(fsys)
+			err := os.Remove(path.Dir().ToString())
+
+			if err != nil {
+				t.Errorf("failed to clean up first: %v", err)
+			}
+
+			gotConfigPath, getErr := getUserConfigPath(tt.fsys)
+			if gotConfigPath == "" || getErr == nil {
```
Comment (gsoltis) [inline cli/internal/config/config_file_test.go:35]: What is this doing? If we've failed to get the path `gotConfigPath == ""` or we've succeeded `getErr == nil`, we do the assignment? 

Presumably we should know which case we want and this should be an assertion instead?

File: cli/internal/config/config_file_test.go [hunk 3]
```diff
@@ -9,6 +9,51 @@ import (
...
+	tests := []struct {
+		name string
+		fsys afero.Fs
+	}{
+		{
+			name: "get doesn't create a path",
+			fsys: fsys,
+		},
+	}
+	for _, tt := range tests {
```
Comment (gsoltis) [inline cli/internal/config/config_file_test.go:24]: Are you planning to add more test cases to this? Otherwise, the table test pattern is probably overkill.

File: cli/internal/config/config_file_test.go [hunk 4]
```diff
@@ -9,6 +9,51 @@ import (
...
+			if err != nil {
+				t.Errorf("failed to clean up first: %v", err)
+			}
+
+			gotConfigPath, getErr := getUserConfigPath(tt.fsys)
+			if gotConfigPath == "" || getErr == nil {
+				gotConfigPath = path
+			}
+			gotConfigDir := gotConfigPath.Dir()
+			getCheck, _ := os.Stat(gotConfigDir.ToString())
```
Comment (gsoltis) [inline cli/internal/config/config_file_test.go:39]: This is maybe a good candidate for `AbsolutePath.DirExists`, a sibling to `AbsolutePath.FileExists`.

File: cli/internal/config/config_file_test.go [hunk 5]
```diff
@@ -9,6 +9,51 @@ import (
...
+			if getCheck != nil {
+				t.Error("getUserConfigPath() had side effects.")
+			}
+
+			createConfigPath, createErr := createUserConfigPath(tt.fsys)
+			if createErr != nil {
+				t.Errorf("createUserConfigPath() errored: %v.", createErr)
+			}
+			createConfigDir := createConfigPath.Dir()
+			createCheck, _ := os.Stat(createConfigDir.ToString())
```
Comment (gsoltis) [inline cli/internal/config/config_file_test.go:49]: As above, maybe worth implementing `AbsolutePath.DirExists`

**Review by gsoltis — APPROVED** [review]
The actual change looks fine, but the test I think could use a little cleanup.

File: cli/internal/config/config_file_test.go (hunk 2 above)
Comment (nathanhammond) [reply cli/internal/config/config_file_test.go:35]: This was the consequence of a boolean algebra reduction, I'll make it more clear what is going on here.

File: cli/internal/config/config_file_test.go (hunk 3 above)
Comment (nathanhammond) [reply cli/internal/config/config_file_test.go:24]: Auto-generated test, 😅 I'll pull the loop.

File: cli/internal/config/config_file_test.go (hunk 2 above)
Comment (nathanhammond) [reply cli/internal/config/config_file_test.go:35]: Good catch! This was *erroneous* boolean algebra reduction.

File: cli/internal/config/config_file_test.go (hunk 4 above)
Comment (nathanhammond) [reply cli/internal/config/config_file_test.go:39]: `DirExists` as an API is a bit confusing. Should it call `Dir` on the path first? Or should it process the entire path? `FileExists` suffers a similar problem in reverse: given a path that exists and is a directory, `FileExists` will return `false`. Expected behavior? Maybe. Confusing? Definitely.

Further, what should it do for symlinks? For example, without checking, I couldn't tell you whether `AbsolutePath.FileExists()` is going to follow a symlink or tell me about the link itself. (Turns out, our current implementation for `FileExists` calls `Lstat`, and returns `!FileInfo.IsDir()`.)

I suspect we might want to align toward `Mode().IsDir()` and `Mode().IsRegular()` which at least implies that we're investigating the `FileInfo`s of the current full `AbsolutePath`. But then there is the question of "how much of the [Mode API](https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/os/types.go;l=35-56) do we want to provide sugar for?" And, most importantly, do we want to distinguish between reading symlinks or not?

We could do something like this, but it gets unwieldy:
```
AbsolutePath.IsDir()
AbsolutePath.IsRegular()
AbsolutePath.IsLink()
AbsolutePath.FollowLinksIsDir()
AbsolutePath.FollowLinksIsRegular()
```

In a "show your work" world I think I might prefer something like:
```
// Always returns a chainable call.
// If it errors, the error gets propagated to the last call.
// Intermediate chainable nodes always return an `APFileInfo`.
// Leaf chainable nodes either return the first `error` or a `bool`
// Errors are coerced to false.
func (ap AbsolutePath) Stat() APFileInfo {}
func (ap AbsolutePath) Lstat() APFileInfo {}

func (fi *APFileInfo) IsDir() bool {}

somePath.Stat().IsDir()
somePath.Lstat().IsDir()
```

Too much design work for a quick usage in a test; I'm going to leave this as is for now and we can circle back to discuss what this API should look like.

File: cli/internal/config/config_file_test.go [hunk 6]
```diff
@@ -9,6 +9,46 @@ import (
 	"github.com/vercel/turborepo/cli/internal/fs"
 )
 
+func Test_UserConfigPath(t *testing.T) {
+	fsys := afero.NewMemMapFs()
+
+	t.Run("get doesn't create a path", func(t *testing.T) {
```
Comment (nathanhammond) [inline cli/internal/config/config_file_test.go:15]: I missed removing this, but caught it in #1339.
