### PR TITLE
Filter in package

### LINKED ISSUE #1528: Non-deterministic scopes identified with changed packages filter
### What version of Turborepo are you using?

1.3.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Given:

1) The following directory structure: 

```
- applications
 | - foo
 | - foo-bar
```

2) Changed files in both `foo` and `foo-bar`

running turbo with a changed files filter (`--filter="[HEAD^1]"` or `--filter="[origin/main]"`, etc) does not consistently return both packages in scope, sometimes only identifying the workspace `foo` as changed.

This bug is specific to workspace directories which are a substring of another workspace directory. If the above example directories were updated to `foo-baz` and `foo-bar`, the issue will not present. 

### Expected Behavior

Changed scopes are correctly & consistently identified by Turbo.

We have identified a potential solution by updating [this hasPrefix check](https://github.com/vercel/turborepo/blob/main/cli/internal/scope/scope.go#L207) to include a trailing `/`.  @wvanrensselaer will follow this issue with a PR shortly!

### To Reproduce

- Clone this [example repo](https://github.com/finn-orsini/turbo-filter-bug)
- `pnpm i`
- Make a change to `foo` and `foo-baz` 
- Run `pnpm run build` from repo root a few times 

Output will sometimes identify both packages: 

```
Packages in Scope
Name    Path
//
foo     foo
foo-baz foo-baz
```

And other times only identify `foo`: 

```
Packages in Scope
Name Path
//
foo  foo
```

### PR DESCRIPTION
**Pull request by nathanhammond**
Previously we didn't properly check for package prefixes being at actual file-addressing boundaries. This PR resolves the issue.

Fixes #1528
Closes #1533

### CODE REVIEW

**Review by tknickman — APPROVED** [review]
Way to avoid the regex 😄

**Comment by jaredpalmer** [comment]
Test failing

File: cli/internal/scope/scope.go [hunk 1]
```diff
@@ -199,12 +200,39 @@ func filterIgnoredFiles(opts *Opts, changedFiles []string) ([]string, error) {
...
+
+		// Same path.
+		if prefixLen == changedFileLen {
+			return true
+		}
+
+		// We know changedFile is longer than packagePath.
+		// We can safely directly index into it.
+		// Look ahead one byte and see if it's the separator.
+		if changedFile[prefixLen] == os.PathSeparator {
```
Comment (helloitsjoe) [inline cli/internal/scope/scope.go:221]: Aha, wish I'd thought of this 😄
