### PR TITLE
Ensure maps are accessed with a lock

### LINKED ISSUE #1433: Exception thrown after upgrading to 1.3.0
### What version of Turborepo are you using?

1.3.0

### What package manager are you using / does the bug impact?

npm, pnpm, Yarn v1, Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Windows

### Describe the Bug

Since updating to 1.3.0, the pipeline that was working fine on 1.2.16 is now throwing an error inside turbo's go code.

`fatal error: concurrent map read and map write`

### Expected Behavior

The build to run.

### To Reproduce

No specific reproduction exists, as it only occurs sometimes and works other times. It's definitely a race condition of some sort. Here is the complete stack trace that it's emitting:

```
> turbo run prebuild build test lint predeploy deploy postdeploy pree2e e2e "--cache-dir=/var/.turbo-cache"
fatal error: concurrent map read and map write
goroutine 229 [running]:
runtime.throw({0x9a46d5?, 0x30?})
	runtime/panic.go:992 +0x71 fp=0xc000fb99f8 sp=0xc000fb99c8 pc=0x435071
runtime.mapaccess2_faststr(0xc000fb9a88?, 0x40d8c7?, {0xc00218a6e0, 0x4b})
	runtime/map_faststr.go:117 +0x3d4 fp=0xc000fb9a60 sp=0xc000fb99f8 pc=0x412f74
github.com/vercel/turborepo/cli/internal/fs.memoizeGetTraversePath.func1({0xc00218a6e0, 0x4b})
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:316 +0x58 fp=0xc000fb9ae0 sp=0xc000fb9a60 pc=0x823a78
github.com/vercel/turborepo/cli/internal/fs.gitStatus({0xc00218a6e0, 0x4b}, {0x0, 0x0, 0x0?})
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:379 +0x33a fp=0xc000fb9c50 sp=0xc000fb9ae0 pc=0x823f3a
github.com/vercel/turborepo/cli/internal/fs.GetPackageDeps({0xc000029400, 0x3a}, 0xc000fb9e60)
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:45 +0x205 fp=0xc000fb9e30 sp=0xc000fb9c50 pc=0x821d05
github.com/vercel/turborepo/cli/internal/taskhash.(*packageFileSpec).hash(0xc000e7fb00, 0xc0008e5440, {0xc000029400, 0x3a})
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:79 +0x85 fp=0xc000fb9e98 sp=0xc000fb9e30 pc=0x899f85
github.com/vercel/turborepo/cli/internal/taskhash.(*Tracker).CalculateFileHashes.func1()
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:190 +0x105 fp=0xc000fb9f78 sp=0xc000fb9e98 pc=0x89ae85
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67 fp=0xc000fb9fe0 sp=0xc000fb9f78 pc=0x856647
runtime.goexit()
	runtime/asm_amd64.s:1571 +0x1 fp=0xc000fb9fe8 sp=0xc000fb9fe0 pc=0x467ac1
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d
goroutine 1 [chan send]:
github.com/vercel/turborepo/cli/internal/taskhash.(*Tracker).CalculateFileHashes(0xc000980960, {0xc000b72a00, 0x34f, 0x7fd062bccfff?}, 0xa, {0xc000029400, 0x3a})
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:202 +0x271
github.com/vercel/turborepo/cli/internal/run.(*run).runOperation(0xc00020e420, 0xc000b231d0, 0xc000b3a6c0, 0xc000b445a0?, {0x3a?, 0xa71620?, 0xd71d00?})
	github.com/vercel/turborepo/cli/internal/run/run.go:270 +0x5b9
github.com/vercel/turborepo/cli/internal/run.(*run).run(0xc00020e420, {0xc00022f400?, 0x9, 0xa})
	github.com/vercel/turborepo/cli/internal/run/run.go:256 +0x5ec
github.com/vercel/turborepo/cli/internal/run.getCmd.func1(0xc000220000?, {0xc00022f400, 0xa?, 0xa?})
	github.com/vercel/turborepo/cli/internal/run/run.go:111 +0xe7
github.com/spf13/cobra.(*Command).execute(0xc000220000, {0xc00001e0e0, 0xa, 0xa})
	github.com/spf13/cobra@v1.3.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000220000)
	github.com/spf13/cobra@v1.3.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.3.0/command.go:902
github.com/vercel/turborepo/cli/internal/run.(*RunCommand).Run(0xc000212168, {0xc00001e0e0, 0xa, 0xa})
	github.com/vercel/turborepo/cli/internal/run/run.go:181 +0x93
github.com/mitchellh/cli.(*CLI).Run(0xc0001c0500)
	github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
main.main.func9(0x992972?, {0x0?, 0x60?}, {0xc00001e0d0?, 0xb, 0xb}, {0x0?, 0xd72760?}, {0x0, 0x0}, ...)
	github.com/vercel/turborepo/cli/cmd/turbo/main.go:171 +0x445
main.main()
	github.com/vercel/turborepo/cli/cmd/turbo/main.go:176 +0xb25
goroutine 17 [syscall]:
os/signal.signal_recv()
	runtime/sigqueue.go:151 +0x2f
os/signal.loop()
	os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x2a
goroutine 33 [chan receive]:
main.watchSignals.func1()
	github.com/vercel/turborepo/cli/cmd/turbo/signals.go:15 +0x31
created by main.watchSignals
	github.com/vercel/turborepo/cli/cmd/turbo/signals.go:14 +0x11a
goroutine 233 [runnable]:
sync.runtime_Semrelease(0x0?, 0xc0?, 0xc46?)
	runtime/sema.go:66 +0x19
sync.(*Mutex).unlockSlow(0x0?, 0x0?)
	sync/mutex.go:237 +0xae
sync.(*Mutex).Unlock(...)
	sync/mutex.go:214
sync.(*RWMutex).Unlock(0xdac470)
	sync/rwmutex.go:208 +0x9b
syscall.forkExec({0xc000909970?, 0x4c?}, {0xc00027d140?, 0x7?, 0xc?}, 0xc0021ce000?)
	syscall/exec_unix.go:216 +0x39d
syscall.StartProcess(...)
	syscall/exec_unix.go:255
os.startProcess({0xc000909970, 0xc}, {0xc00027d140, 0x7, 0xc}, 0xc000fcb9c0)
	os/exec_posix.go:54 +0x335
os.StartProcess({0xc000909970, 0xc}, {0xc00027d140, 0x7, 0xc}, 0xc0000e5a00?)
	os/exec.go:109 +0x5a
os/exec.(*Cmd).Start(0xc001d2d340)
	os/exec/exec.go:425 +0x5e5
github.com/vercel/turborepo/cli/internal/fs.runGitCommand(0x8f11c0?, {0x9934fc, 0x6}, 0x9df898)
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:214 +0x11c
github.com/vercel/turborepo/cli/internal/fs.gitStatus({0xc00218b680, 0x4c}, {0x0, 0x0, 0x0?})
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:371 +0x2f6
github.com/vercel/turborepo/cli/internal/fs.GetPackageDeps({0xc000029400, 0x3a}, 0xc000fcbe60)
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:45 +0x205
github.com/vercel/turborepo/cli/internal/taskhash.(*packageFileSpec).hash(0xc000dfe870, 0xc00067de60, {0xc000029400, 0x3a})
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:79 +0x85
github.com/vercel/turborepo/cli/internal/taskhash.(*Tracker).CalculateFileHashes.func1()
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:190 +0x105
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d
goroutine 226 [IO wait]:
internal/poll.runtime_pollWait(0x7fd062729798, 0x72)
	runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc0021b2240?, 0xc00209f000?, 0x1)
	internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc0021b2240, {0xc00209f000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
	os/file_posix.go:31
os.(*File).Read(0xc0005f97d8, {0xc00209f000?, 0x463b5d?, 0x0?})
	os/file.go:119 +0x5e
bufio.(*Reader).fill(0xc0020a6120)
	bufio/bufio.go:106 +0x103
bufio.(*Reader).ReadSlice(0xc0020a6120, 0x0?)
	bufio/bufio.go:371 +0x2f
github.com/vercel/turborepo/cli/internal/encoding/gitoutput.(*Reader).readEntry(0xc001f7a4d0)
	github.com/vercel/turborepo/cli/internal/encoding/gitoutput/gitoutput.go:249 +0x3c
github.com/vercel/turborepo/cli/internal/encoding/gitoutput.(*Reader).readRecord(0xc001f7a4d0, {0x0, 0xc001d2d2b8?, 0x0})
	github.com/vercel/turborepo/cli/internal/encoding/gitoutput/gitoutput.go:296 +0x45
github.com/vercel/turborepo/cli/internal/encoding/gitoutput.(*Reader).ReadAll(0xa71ce0?)
	github.com/vercel/turborepo/cli/internal/encoding/gitoutput/gitoutput.go:233 +0x65
github.com/vercel/turborepo/cli/internal/fs.runGitCommand(0x8f11c0?, {0x9934fc, 0x6}, 0x9df898)
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:220 +0x205
github.com/vercel/turborepo/cli/internal/fs.gitStatus({0xc0021bc480, 0x51}, {0x0, 0x0, 0x0?})
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:371 +0x2f6
github.com/vercel/turborepo/cli/internal/fs.GetPackageDeps({0xc000029400, 0x3a}, 0xc000fbbe60)
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:45 +0x205
github.com/vercel/turborepo/cli/internal/taskhash.(*packageFileSpec).hash(0xc000e99860, 0xc00067d440, {0xc000029400, 0x3a})
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:79 +0x85
github.com/vercel/turborepo/cli/internal/taskhash.(*Tracker).CalculateFileHashes.func1()
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:190 +0x105
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d
goroutine 232 [IO wait]:
internal/poll.runtime_pollWait(0x7fd062611ee8, 0x72)
	runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc001e316e0?, 0xc001fb9000?, 0x1)
	internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc001e316e0, {0xc001fb9000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
	os/file_posix.go:31
os.(*File).Read(0xc000a246f0, {0xc001fb9000?, 0x463b5d?, 0x0?})
	os/file.go:119 +0x5e
bufio.(*Reader).fill(0xc001e318c0)
	bufio/bufio.go:106 +0x103
bufio.(*Reader).ReadSlice(0xc001e318c0, 0x0?)
	bufio/bufio.go:371 +0x2f
github.com/vercel/turborepo/cli/internal/encoding/gitoutput.(*Reader).readEntry(0xc00170bad0)
	github.com/vercel/turborepo/cli/internal/encoding/gitoutput/gitoutput.go:249 +0x3c
github.com/vercel/turborepo/cli/internal/encoding/gitoutput.(*Reader).readRecord(0xc00170bad0, {0x0, 0xc001e50918?, 0x0})
	github.com/vercel/turborepo/cli/internal/encoding/gitoutput/gitoutput.go:296 +0x45
github.com/vercel/turborepo/cli/internal/encoding/gitoutput.(*Reader).ReadAll(0xa71ce0?)
	github.com/vercel/turborepo/cli/internal/encoding/gitoutput/gitoutput.go:233 +0x65
github.com/vercel/turborepo/cli/internal/fs.runGitCommand(0x8f11c0?, {0x9934fc, 0x6}, 0x9df898)
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:220 +0x205
github.com/vercel/turborepo/cli/internal/fs.gitStatus({0xc001f88850, 0x67}, {0x0, 0x0, 0x0?})
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:371 +0x2f6
github.com/vercel/turborepo/cli/internal/fs.GetPackageDeps({0xc000029400, 0x3a}, 0xc000fbfe60)
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:45 +0x205
github.com/vercel/turborepo/cli/internal/taskhash.(*packageFileSpec).hash(0xc000e7e870, 0xc0008bcfc0, {0xc000029400, 0x3a})
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:79 +0x85
github.com/vercel/turborepo/cli/internal/taskhash.(*Tracker).CalculateFileHashes.func1()
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:190 +0x105
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d
goroutine 234 [IO wait]:
internal/poll.runtime_pollWait(0x7fd062611768, 0x72)
	runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc001a7f080?, 0xc00209b000?, 0x1)
	internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc001a7f080, {0xc00209b000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
	os/file_posix.go:31
os.(*File).Read(0xc0008244a0, {0xc00209b000?, 0x463b5d?, 0x0?})
	os/file.go:119 +0x5e
bufio.(*Reader).fill(0xc001273c20)
	bufio/bufio.go:106 +0x103
bufio.(*Reader).ReadSlice(0xc001273c20, 0x0?)
	bufio/bufio.go:371 +0x2f
github.com/vercel/turborepo/cli/internal/encoding/gitoutput.(*Reader).readEntry(0xc001f7a210)
	github.com/vercel/turborepo/cli/internal/encoding/gitoutput/gitoutput.go:249 +0x3c
github.com/vercel/turborepo/cli/internal/encoding/gitoutput.(*Reader).readRecord(0xc001f7a210, {0x0, 0xc001a7abd8?, 0x0})
	github.com/vercel/turborepo/cli/internal/encoding/gitoutput/gitoutput.go:296 +0x45
github.com/vercel/turborepo/cli/internal/encoding/gitoutput.(*Reader).ReadAll(0xa71ce0?)
	github.com/vercel/turborepo/cli/internal/encoding/gitoutput/gitoutput.go:233 +0x65
github.com/vercel/turborepo/cli/internal/fs.runGitCommand(0x8f11c0?, {0x9934fc, 0x6}, 0x9df898)
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:220 +0x205
github.com/vercel/turborepo/cli/internal/fs.gitStatus({0xc001d9f8c0, 0x53}, {0x0, 0x0, 0x0?})
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:371 +0x2f6
github.com/vercel/turborepo/cli/internal/fs.GetPackageDeps({0xc000029400, 0x3a}, 0xc00098de60)
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:45 +0x205
github.com/vercel/turborepo/cli/internal/taskhash.(*packageFileSpec).hash(0xc000e92420, 0xc000226d80, {0xc000029400, 0x3a})
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:79 +0x85
github.com/vercel/turborepo/cli/internal/taskhash.(*Tracker).CalculateFileHashes.func1()
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:190 +0x105
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d
goroutine 230 [semacquire]:
sync.runtime_SemacquireMutex(0x60?, 0x0?, 0xc0021bdd40?)
	runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xdac470)
	sync/mutex.go:162 +0x165
sync.(*Mutex).Lock(...)
	sync/mutex.go:81
sync.(*RWMutex).Lock(0xc0021c6800?)
	sync/rwmutex.go:139 +0x36
syscall.forkExec({0xc000909a20?, 0x58?}, {0xc00027d2c0?, 0x7?, 0xc?}, 0xc0021dc000?)
	syscall/exec_unix.go:200 +0x2df
syscall.StartProcess(...)
	syscall/exec_unix.go:255
os.startProcess({0xc000909a20, 0xc}, {0xc00027d2c0, 0x7, 0xc}, 0xc000ed19c0)
	os/exec_posix.go:54 +0x335
os.StartProcess({0xc000909a20, 0xc}, {0xc00027d2c0, 0x7, 0xc}, 0xc00078b520?)
	os/exec.go:109 +0x5a
os/exec.(*Cmd).Start(0xc001d2d4a0)
	os/exec/exec.go:425 +0x5e5
github.com/vercel/turborepo/cli/internal/fs.runGitCommand(0x8f11c0?, {0x9934fc, 0x6}, 0x9df898)
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:214 +0x11c
github.com/vercel/turborepo/cli/internal/fs.gitStatus({0xc0021bdb00, 0x58}, {0x0, 0x0, 0x0?})
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:371 +0x2f6
github.com/vercel/turborepo/cli/internal/fs.GetPackageDeps({0xc000029400, 0x3a}, 0xc000ed1e60)
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:45 +0x205
github.com/vercel/turborepo/cli/internal/taskhash.(*packageFileSpec).hash(0xc000e92270, 0xc000673d40, {0xc000029400, 0x3a})
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:79 +0x85
github.com/vercel/turborepo/cli/internal/taskhash.(*Tracker).CalculateFileHashes.func1()
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:190 +0x105
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d
goroutine 228 [IO wait]:
internal/poll.runtime_pollWait(0x7fd062729888, 0x72)
	runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc001e314a0?, 0xc00209e000?, 0x1)
	internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc001e314a0, {0xc00209e000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
	os/file_posix.go:31
os.(*File).Read(0xc000a246d0, {0xc00209e000?, 0x7fd062bccfff?, 0x0?})
	os/file.go:119 +0x5e
bufio.(*Reader).fill(0xc001273c80)
	bufio/bufio.go:106 +0x103
bufio.(*Reader).ReadSlice(0xc001273c80, 0xf8?)
	bufio/bufio.go:371 +0x2f
github.com/vercel/turborepo/cli/internal/encoding/gitoutput.(*Reader).readEntry(0xc001f7a2c0)
	github.com/vercel/turborepo/cli/internal/encoding/gitoutput/gitoutput.go:249 +0x3c
github.com/vercel/turborepo/cli/internal/encoding/gitoutput.(*Reader).readRecord(0xc001f7a2c0, {0x0, 0xc001e507b8?, 0x0})
	github.com/vercel/turborepo/cli/internal/encoding/gitoutput/gitoutput.go:296 +0x45
github.com/vercel/turborepo/cli/internal/encoding/gitoutput.(*Reader).ReadAll(0xa71ce0?)
	github.com/vercel/turborepo/cli/internal/encoding/gitoutput/gitoutput.go:233 +0x65
github.com/vercel/turborepo/cli/internal/fs.runGitCommand(0x8f11c0?, {0x9934fc, 0x6}, 0x9df898)
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:220 +0x205
github.com/vercel/turborepo/cli/internal/fs.gitStatus({0xc001f8a820, 0x4f}, {0x0, 0x0, 0x28?})
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:371 +0x2f6
github.com/vercel/turborepo/cli/internal/fs.GetPackageDeps({0xc000029400, 0x3a}, 0xc00098fe60)
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:45 +0x205
github.com/vercel/turborepo/cli/internal/taskhash.(*packageFileSpec).hash(0xc000e93980, 0xc0008950e0, {0xc000029400, 0x3a})
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:79 +0x85
github.com/vercel/turborepo/cli/internal/taskhash.(*Tracker).CalculateFileHashes.func1()
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:190 +0x105
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d
goroutine 227 [IO wait]:
internal/poll.runtime_pollWait(0x7fd062729018, 0x72)
	runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc001273f80?, 0xc001fba000?, 0x1)
	internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc001273f80, {0xc001fba000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
	os/file_posix.go:31
os.(*File).Read(0xc0009a0be8, {0xc001fba000?, 0x7fd062bccfff?, 0x0?})
	os/file.go:119 +0x5e
bufio.(*Reader).fill(0xc001e31920)
	bufio/bufio.go:106 +0x103
bufio.(*Reader).ReadSlice(0xc001e31920, 0xf8?)
	bufio/bufio.go:371 +0x2f
github.com/vercel/turborepo/cli/internal/encoding/gitoutput.(*Reader).readEntry(0xc00170bb80)
	github.com/vercel/turborepo/cli/internal/encoding/gitoutput/gitoutput.go:249 +0x3c
github.com/vercel/turborepo/cli/internal/encoding/gitoutput.(*Reader).readRecord(0xc00170bb80, {0x0, 0xc001f4ea78?, 0x0})
	github.com/vercel/turborepo/cli/internal/encoding/gitoutput/gitoutput.go:296 +0x45
github.com/vercel/turborepo/cli/internal/encoding/gitoutput.(*Reader).ReadAll(0xa71ce0?)
	github.com/vercel/turborepo/cli/internal/encoding/gitoutput/gitoutput.go:233 +0x65
github.com/vercel/turborepo/cli/internal/fs.runGitCommand(0x8f11c0?, {0x9934fc, 0x6}, 0x9df898)
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:220 +0x205
github.com/vercel/turborepo/cli/internal/fs.gitStatus({0xc001f37a40, 0x54}, {0x0, 0x0, 0x0?})
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:371 +0x2f6
github.com/vercel/turborepo/cli/internal/fs.GetPackageDeps({0xc000029400, 0x3a}, 0xc000fc9e60)
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:45 +0x205
github.com/vercel/turborepo/cli/internal/taskhash.(*packageFileSpec).hash(0xc000e83560, 0xc0008f3320, {0xc000029400, 0x3a})
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:79 +0x85
github.com/vercel/turborepo/cli/internal/taskhash.(*Tracker).CalculateFileHashes.func1()
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:190 +0x105
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d
goroutine 231 [runnable]:
syscall.Getenv({0x99257c, 0x4})
	syscall/env_unix.go:90 +0x1b8
os.Getenv({0x99257c, 0x4})
	os/env.go:103 +0x34
os/exec.LookPath({0x99205c, 0x3})
	os/exec/lp_unix.go:47 +0x5d
os/exec.Command({0x99205c, 0x3}, {0xc000fbdba0, 0x2, 0xc000fbdb80?})
	os/exec/exec.go:175 +0x1a5
github.com/vercel/turborepo/cli/internal/fs.gitHashObject({0xc000029400, 0x3a}, {0xc001ebe750, 0x1, 0x1})
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:100 +0xe5
github.com/vercel/turborepo/cli/internal/fs.GetPackageDeps({0xc000029400, 0x3a}, 0xc000fbde60)
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:60 +0x512
github.com/vercel/turborepo/cli/internal/taskhash.(*packageFileSpec).hash(0xc000e7fec0, 0xc0008d2900, {0xc000029400, 0x3a})
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:79 +0x85
github.com/vercel/turborepo/cli/internal/taskhash.(*Tracker).CalculateFileHashes.func1()
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:190 +0x105
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d
goroutine 225 [IO wait]:
internal/poll.runtime_pollWait(0x7fd062611858, 0x72)
	runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc001ba7200?, 0xc001f9a000?, 0x1)
	internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc001ba7200, {0xc001f9a000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
	os/file_posix.go:31
os.(*File).Read(0xc0005f96c8, {0xc001f9a000?, 0x7fd062bccfff?, 0x0?})
	os/file.go:119 +0x5e
bufio.(*Reader).fill(0xc001e31200)
	bufio/bufio.go:106 +0x103
bufio.(*Reader).ReadSlice(0xc001e31200, 0xf8?)
	bufio/bufio.go:371 +0x2f
github.com/vercel/turborepo/cli/internal/encoding/gitoutput.(*Reader).readEntry(0xc00170b600)
	github.com/vercel/turborepo/cli/internal/encoding/gitoutput/gitoutput.go:249 +0x3c
github.com/vercel/turborepo/cli/internal/encoding/gitoutput.(*Reader).readRecord(0xc00170b600, {0x0, 0xc001d2c7b8?, 0x0})
	github.com/vercel/turborepo/cli/internal/encoding/gitoutput/gitoutput.go:296 +0x45
github.com/vercel/turborepo/cli/internal/encoding/gitoutput.(*Reader).ReadAll(0xa71ce0?)
	github.com/vercel/turborepo/cli/internal/encoding/gitoutput/gitoutput.go:233 +0x65
github.com/vercel/turborepo/cli/internal/fs.runGitCommand(0x8f11c0?, {0x9934fc, 0x6}, 0x9df898)
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:220 +0x205
github.com/vercel/turborepo/cli/internal/fs.gitStatus({0xc001d70d20, 0x59}, {0x0, 0x0, 0x0?})
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:371 +0x2f6
github.com/vercel/turborepo/cli/internal/fs.GetPackageDeps({0xc000029400, 0x3a}, 0xc000fc5e60)
	github.com/vercel/turborepo/cli/internal/fs/package_deps_hash.go:45 +0x205
github.com/vercel/turborepo/cli/internal/taskhash.(*packageFileSpec).hash(0xc000e83230, 0xc00089f7a0, {0xc000029400, 0x3a})
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:79 +0x85
github.com/vercel/turborepo/cli/internal/taskhash.(*Tracker).CalculateFileHashes.func1()
	github.com/vercel/turborepo/cli/internal/taskhash/taskhash.go:190 +0x105
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d
```

### PR DESCRIPTION
**Pull request by gsoltis**
Also ensure mutex is captured by reference, rather than by value.

Fixes #1433

### CODE REVIEW

**Review by jaredpalmer — APPROVED** [review]

File: cli/internal/fs/package_deps_hash.go [hunk 1]
```diff
@@ -308,13 +308,15 @@ func getTraversePath(rootPath turbopath.AbsoluteSystemPath) (turbopath.RelativeU
 // Don't shell out if we already know where you are in the repository.
 // `memoize` is a good candidate for generics.
 func memoizeGetTraversePath() func(turbopath.AbsoluteSystemPath) (turbopath.RelativeUnixPath, error) {
-	cacheMutex := sync.RWMutex{}
+	cacheMutex := &sync.RWMutex{}
```
Comment (nathanhammond) [inline cli/internal/fs/package_deps_hash.go:311]: Since it's caught in a closure I didn't believe it was necessary to indirect it? Maybe my mental model for how closure scoped vars get addressed in Go is wrong?

***

[type RWMutex](https://pkg.go.dev/sync#RWMutex)

    [func (rw *RWMutex) Lock()](https://pkg.go.dev/sync#RWMutex.Lock)
    [func (rw *RWMutex) RLock()](https://pkg.go.dev/sync#RWMutex.RLock)
    [func (rw *RWMutex) RLocker() Locker](https://pkg.go.dev/sync#RWMutex.RLocker)
    [func (rw *RWMutex) RUnlock()](https://pkg.go.dev/sync#RWMutex.RUnlock)
    [func (rw *RWMutex) TryLock() bool](https://pkg.go.dev/sync#RWMutex.TryLock)
    [func (rw *RWMutex) TryRLock() bool](https://pkg.go.dev/sync#RWMutex.TryRLock)
    [func (rw *RWMutex) Unlock()](https://pkg.go.dev/sync#RWMutex.Unlock)

Given these method signatures, why did Go let me do this?

**Review by nathanhammond — COMMENTED** [review]
Thanks for cleaning this up! 😅

I have questions about *why* this failed that I'm going to spend some time learning today.

File: cli/internal/fs/package_deps_hash.go (hunk 1 above)
Comment (gsoltis) [reply cli/internal/fs/package_deps_hash.go:311]: On a second readthrough, I think you're right. The fact that it's in a closure and not an argument means it's captured by reference, and the style guide at least suggests that we ought to change it to [`var cacheMutex sync.RWMutex`](https://github.com/uber-go/guide/blob/master/style.md#zero-value-mutexes-are-valid). The culprit was likely not locking around the reads from the maps.

For the methods on `RWMutex`, unfortunately, I _believe_ Go will let you call them with or without a reference, without having an indication at the call site. The implementation is choosing whether the receiver is passed by reference or by value. 

If you haven't already seen it, I recommend reading [Uber's analysis of data races in Go](https://eng.uber.com/data-race-patterns-in-go/). I think I confused the interaction between 1. and 4. in that article, but got 3. correct.

Comment (nathanhammond) [reply cli/internal/fs/package_deps_hash.go:311]: Interesting that the zero value of a mutex is a valid mutex.

The thing that threw me here was not knowing I needed a reader lock; I (incorrectly) assumed that locks during writes would be enough, but realize now that it doesn't either implicitly lock out readers during the write lock and the corollary implication that writes aren't necessarily atomic.

Arguably this should be using `sync.Map` but that loses types and becomes a pain to use.

The Uber data races post was in a browser tab yesterday as to-read, and, well, now it has been read. About 12 hours too late.
