### PR TITLE
fix: treat symlink directory as directory

### LINKED ISSUE #531: error hashing files when globalDependencies contains a symlinked directory
### What version of Turborepo are you using?

1.0.24

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

If a symlinked directory exists in the in a globalDependencies matching path, turborepo will throw with `error hashing files. make sure that git has been initialized git hash-object exited with status: exit status 128`.

This is because we collect all the file names to pass to git hash-object by grabbing all via `GlobFiles->Walk->WalkMode`. In the case of a symlinked directory, `info.isDir()=false`, causing a directory path to be passed to `git hash-object` (which is dissallowed)

### Expected Behavior

Symlinked directories also be excluded. Fortunately, `godirwalk` already supported this via `IsDirOrSymlinkToDir`

### To Reproduce

1. in `kitchen-sink` example, add turbo config:
```
    "globalDependencies": [
      "node_modules/**"
    ],
```
(just as an example)

2. Run `yarn build`
3. Build command will error

### PR DESCRIPTION
**Pull request by markjm**
Fixes #531

### CODE REVIEW

File: cli/internal/fs/copy_file.go [hunk 1]
```diff
@@ -79,17 +79,17 @@ func Walk(rootPath string, callback func(name string, isDir bool) error) error {
...
-			return callback(name, info.IsDir(), info.ModeType())
+			if isDirLike, err := info.IsDirOrSymlinkToDir(); err == nil {
+				return callback(name, isDirLike, info.ModeType())
+			} else {
+				return err
+			}
 		},
-		Unsorted: true,
+		Unsorted:            true,
+		AllowNonDirectory:   true,
```
Comment (markjm) [inline cli/internal/fs/copy_file.go:91]: This setting just does what the deleted compat code does already

File: cli/internal/fs/copy_file.go [hunk 2]
```diff
@@ -79,17 +79,17 @@ func Walk(rootPath string, callback func(name string, isDir bool) error) error {
...
+		FollowSymbolicLinks: false,
```
Comment (markjm) [inline cli/internal/fs/copy_file.go:92]: Defaults to `false` anyway, but setting it explicitly, because some functionality depends on not following symlinks. For example, following symlinks in node_modules a yarn workspace will send you right back to the source code.

**Review by jaredpalmer — APPROVED** [review]

**Review by jaredpalmer — APPROVED** [review]

**Comment by jaredpalmer** [comment]
@markjm This is causing pnpm symlinks to become inconsistent if the user moves a folder. Reverting this change fixes the problem. Can you investigate? https://github.com/vercel/turborepo/issues/549

**Comment by markjm** [comment]
> @markjm This is causing pnpm symlinks to become inconsistent/not be recognized (especially when user moves a folder). Reverting this change fixes the problem. Can you investigate https://github.com/vercel/turborepo/issues/549?
> 
> 
> 
> Notice in screenshot how the apps are not recognized as result of globs?
> 
> 
> 
> CleanShot 2022-01-17 at 15 43 27@2x
> 
> 
> 
> CleanShot 2022-01-17 at 15 44 42@2x
> 
>  

Sure. In the meantime, it seems pnpm usage is more common than the frequency of the original bug I was trying to fix - so should probably just revert this for now
