### PR TITLE
Stop hitting remote cache after a few failures

### LINKED ISSUE #541: Build waits 90 seconds between packages when caching server is offline
### What version of Turborepo are you using?

1.0.25

### What package manager are you using / does the bug impact?

npm, pnpm, Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

When a caching server is offline or otherwise unreachable, it greatly slows down build speed as every request waits 90 seconds before timing out and running the local build step. This happens for every package, turning a 40 package build into something like an hour long build.

### Expected Behavior

Ideally, caching would be an add-on to a local build and not blocking. 

A per-run configurable timeout would be great. Basically, if the server fails to respond, or is unreachable after a set time, fall back to local automatically for the rest of the run.

I really want to adopt this, but don't want to take the whole team out if they're offline or if our caching server goes down :swe

Loving it so far. Thanks!

### To Reproduce

`npx turbo run build --api="http://offline-caching.server" --token=token --team=team_name`

### PR DESCRIPTION
**Pull request by jaredpalmer**
Close #541 

When the remote cache fails or timesout more than `n` times (twice at the moment), `turbo` will cease trying to hit the remote cache.

### CODE REVIEW

**Review by gaspar09 — DISMISSED** [review]

File: cli/internal/client/client.go [hunk 1]
```diff
@@ -30,21 +32,55 @@ func (api *ApiClient) SetToken(token string) {
 
 // New creates a new ApiClient
 func NewClient(baseUrl string, logger hclog.Logger, turboVersion string) *ApiClient {
-	return &ApiClient{
-		baseUrl:      baseUrl,
-		turboVersion: turboVersion,
+	client := &ApiClient{
+		baseUrl:          baseUrl,
+		turboVersion:     turboVersion,
+		CurrentFailCount: 0,
```
Comment (gsoltis) [inline cli/internal/client/client.go:38]: Based on the [uber style guide](https://github.com/uber-go/guide/blob/master/style.md#omit-zero-value-fields-in-structs) I would leave out this particular field, unless there's a comment for why we're explicitly setting it to `0`, which would happen automatically.

File: cli/internal/client/client.go [hunk 2]
```diff
@@ -30,21 +32,55 @@ func (api *ApiClient) SetToken(token string) {
...
 			Backoff:      retryablehttp.DefaultBackoff,
 			Logger:       logger,
 		},
 	}
+	return client
+}
+
+func (client *ApiClient) retryCachePolicy(resp *http.Response, err error) (bool, error) {
+	if err != nil {
+		if v, ok := err.(*url.Error); ok {
```
Comment (gsoltis) [inline cli/internal/client/client.go:55]: It might be clearer in these situations to use something like [`errors.Is`](https://pkg.go.dev/errors#Is) or [`errors.As`](https://pkg.go.dev/errors#As). Some examples [here](https://github.com/uber-go/guide/blob/master/style.md#error-types)

File: cli/internal/client/client.go [hunk 3]
```diff
@@ -30,21 +32,55 @@ func (api *ApiClient) SetToken(token string) {
...
+			// Don't retry if the error was due to TLS cert verification failure.
+			if _, ok := v.Err.(x509.UnknownAuthorityError); ok {
```
Comment (gsoltis) [inline cli/internal/client/client.go:57]: I think this is a good candidate for [`errors.Is`](https://pkg.go.dev/errors#Is)

File: cli/internal/client/client.go [hunk 4]
```diff
@@ -17,9 +18,10 @@ import (
 
 type ApiClient struct {
 	// The api's base URL
-	baseUrl      string
-	Token        string
-	turboVersion string
+	baseUrl          string
+	Token            string
+	turboVersion     string
+	CurrentFailCount uint64
```
Comment (gsoltis) [inline cli/internal/client/client.go:24]: Can you add a comment that this field is intended to be read and written from multiple goroutines? I know that's probably the default in Go, but it seems worth calling out because I don't think anything else in the struct is intended to be modified concurrently. See below for a note on `HttpClient` though.

File: cli/internal/client/client.go [hunk 5]
```diff
@@ -63,14 +99,32 @@ func (c *ApiClient) PutArtifact(hash string, teamId string, slug string, duratio
...
+	req, err := retryablehttp.NewRequest(http.MethodPut, c.makeUrl("/v8/artifacts/"+hash+encoded), rawBody)
 	req.Header.Set("Content-Type", "application/octet-stream")
 	req.Header.Set("x-artifact-duration", fmt.Sprintf("%v", duration))
 	req.Header.Set("Authorization", "Bearer "+c.Token)
 	req.Header.Set("User-Agent", c.UserAgent())
 	if err != nil {
 		return fmt.Errorf("[WARNING] Invalid cache URL: %w", err)
 	}
+
+	c.HttpClient.CheckRetry = func(ctx context.Context, resp *http.Response, err error) (bool, error) {
```
Comment (gsoltis) [inline cli/internal/client/client.go:116]: This looks like a potentially-concurrent write to `c.HttpClient`, if the `ApiClient` is used in multiple goroutines. What about adding this function in `NewClient`?

File: cli/internal/client/client.go [hunk 6]
```diff
@@ -87,12 +141,30 @@ func (c *ApiClient) FetchArtifact(hash string, teamId string, slug string, rawBo
...
+	}
+	req, err := retryablehttp.NewRequest(http.MethodGet, c.makeUrl("/v8/artifacts/"+hash+encoded), nil)
 	req.Header.Set("Authorization", "Bearer "+c.Token)
 	req.Header.Set("User-Agent", c.UserAgent())
 	if err != nil {
-		return nil, fmt.Errorf("[WARNING] Invalid cache URL: %w", err)
+		return nil, fmt.Errorf("invalid cache URL: %w", err)
 	}
+
+	c.HttpClient.CheckRetry = func(ctx context.Context, resp *http.Response, err error) (bool, error) {
```
Comment (gsoltis) [inline cli/internal/client/client.go:156]: Another potentially-concurrent write to `c.HttpClient`

File: cli/internal/cache/cache.go [hunk 7]
```diff
@@ -53,39 +55,42 @@ type cacheMultiplexer struct {
...
 func (mplex cacheMultiplexer) Fetch(target string, key string, files []string) (bool, []string, error) {
 	// Retrieve from caches sequentially; if we did them simultaneously we could
 	// easily write the same file from two goroutines at once.
 	for i, cache := range mplex.caches {
-		if ok, actualFiles, _ := cache.Fetch(target, key, files); ok {
+		if ok, actualFiles, err := cache.Fetch(target, key, files); ok {
 			// Store this into other caches
 			mplex.storeUntil(target, key, 0, actualFiles, i)
-			return ok, actualFiles, nil
+			return ok, actualFiles, err
```
Comment (gsoltis) [inline cli/internal/cache/cache.go:93]: The error we're returning here is from `cache.Fetch`, but we have just called a potentially-failing `mplex.storeUntil`. I think at the very least we ought to have a comment as to why we're ignoring that error.

File: cli/internal/cache/cache.go [hunk 8]
```diff
@@ -53,39 +55,42 @@ type cacheMultiplexer struct {
...
 // storeUntil stores artifacts into higher priority caches than the given one.
 // Used after artifact retrieval to ensure we have them in eg. the directory cache after
 // downloading from the RPC cache.
 // This is a little inefficient since we could write the file to plz-out then copy it to the dir cache,
 // but it's hard to fix that without breaking the cache abstraction.
-func (mplex cacheMultiplexer) storeUntil(target string, key string, duration int, outputGlobs []string, stopAt int) {
+func (mplex cacheMultiplexer) storeUntil(target string, key string, duration int, outputGlobs []string, stopAt int) error {
 	// Attempt to store on all caches simultaneously.
-	var wg sync.WaitGroup
+	g := new(errgroup.Group)
```
Comment (gsoltis) [inline cli/internal/cache/cache.go:68]: Prefer `g := &errgroup.Group{}` to `new()` usages, based on [style guide](https://github.com/uber-go/guide/blob/master/style.md#initializing-struct-references)

File: cli/internal/client/client.go (hunk 4 above)
Comment (gsoltis) [inline cli/internal/client/client.go:24]: As best I can tell, we are not checking this value before initiating a new request on an existing `ApiClient`, only for retries after each request fails. Is that intended?

**Review by gsoltis — CHANGES_REQUESTED** [review]

File: cli/internal/client/client.go (hunk 4 above)
Comment (gsoltis) [reply cli/internal/client/client.go:24]: Ah, my mistake, this happens outside of the `ApiClient`. It might be a good idea to encapsulate that a bit better, so that calling code does not need to check.

File: cli/internal/cache/cache.go (hunk 8 above)
Comment (gsoltis) [reply cli/internal/cache/cache.go]: Done.

File: cli/internal/client/client.go (hunk 3 above)
Comment (gsoltis) [reply cli/internal/client/client.go]: `errors.As`, but done.

**Review by gsoltis — APPROVED** [review]

**Review by gsoltis — CHANGES_REQUESTED** [review]
This looks like it's coming along. 

One general Go comment to add: for methods or functions that are not intended to be used outside of a package, they can be kept private by starting the name with a lowercase letter. So `IsProtocolExternal` can be `isProtocolExternal`.  Test code is typically part of the same package, so this does not impact the ability to write tests for this code.

Along those lines, it might be nice to have a quick test demonstrating some typical internal vs external references.

**Comment by gsoltis** [comment]
Whoa, weird, that was a comment I made for a different PR authored via VSCode. I was wondering where it went...
