### PR TITLE
Handle pnpm resolving a dependency to multiple versions

### LINKED ISSUE #2075: Cache hash changes on windows without any change
### What version of Turborepo are you using?

1.5.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

I created a [simple example repo](https://github.com/byCedric/expo-monorepo-example) with pnpm and turbo. When I played around, I noticed my cache hits were flaky on Windows. I'm not sure what's going on here.

I get different cache key results without changing anything within the repo or having any open process accessing the files.

Here is the log with multiple `pnpm build --dry-run` results without changing anything. 
> Notice how the order of `Dependenceis` randomly changes, and the `Hash` too for all except `@acme/eslint-config`.

[turbo-repo-log.txt](https://github.com/vercel/turborepo/files/9640915/turbo-repo-log.txt)

### Expected Behavior

Without changing files in the repository, I expect the hash to stay the same. In this case, that works inside a docker instance (tested with `node:16-alpine` - same machine, docker desktop) but not in just Windows. I'm using:

```
Edition: Windows 11 Pro
Version: 22H2
OS build: 22621.521
Experience: Windows Feature Experience Pack 1000.22634.1000.0
```

```
Windows Terminal
Version: 1.14.2282.0
```

### To Reproduce

Also, I tested the same thing in GHA to rule out issues with my machine. [You can see the same thing happening there](https://github.com/byCedric/expo-monorepo-example/actions/runs/3122544115):
  - ubuntu provides the same hash more often ([see run](https://github.com/byCedric/expo-monorepo-example/actions/runs/3122544115/jobs/5064552018#step:5:24))
    > Edit: seems also to be an issue there, mostly in the **apps/\*** projects, but I have no idea why.
  - windows provides what seems to be "random" hashes most of the time ([see run](https://github.com/byCedric/expo-monorepo-example/actions/runs/3122544115/jobs/5064552032#step:5:24))

Or try it locally (it requires Windows).

- `$ git clone git@github.com:byCedric/expo-monorepo-example.git ./windows-hash-issue`
- `$ cd ./windows-hash-issue`
- `$ pnpm i; pnpm build`
- Now, without doing anything, run `$ pnpm build --dry-run` multiple times.
- Check the `Hash` and `Cached (Local)`, they change without any changes

### PR DESCRIPTION
**Pull request by gsoltis**
- `pnpm` can resolve multiple versions of a package. Resolve the package dependency specific to the workspace that asked for it. 
 - handle "exclusions" in `pnpm-workspace.yaml` so that we don't try to resolve non-existent workspaces

Fixes #2075

### CODE REVIEW

File: cli/internal/context/context.go [hunk 1]
```diff
@@ -277,7 +277,7 @@ func (c *Context) populateTopologicGraphForPackageJSON(pkg *fs.PackageJSON, root
 	pkg.TransitiveDeps = []string{}
 	seen := mapset.NewSet()
 	var lockfileWg sync.WaitGroup
-	c.resolveDepGraph(&lockfileWg, pkg.UnresolvedExternalDeps, externalDepSet, seen, pkg)
+	c.resolveDepGraph(&lockfileWg, pkg.Name, pkg.UnresolvedExternalDeps, externalDepSet, seen, pkg)
```
Comment (chris-olszewski) [inline cli/internal/context/context.go:280]: We should be passing down `pkg.Dir.ToUnixPath().ToString()` since both pnpm and Yarn identify workspace projects by path and not by name.

Comment (chris-olszewski) [reply cli/internal/context/context.go:280]: Other thing we need to do is to special case on when `pkg` is the root package and pass `.`

File: cli/internal/lockfile/pnpm_lockfile.go [hunk 2]
```diff
@@ -255,30 +255,33 @@ func (p *PnpmLockfile) Patches() []turbopath.AnchoredUnixPath {
...
-				if resolvedVersion, ok := importer.OptionalDependencies[name]; ok {
-					return resolvedVersion, true
-				}
-
-				panic(fmt.Sprintf("Unable to find resolved version for %s@%s in %s", name, specifier, workspacePkg))
-			}
-		}
+	importer, ok := p.Importers[workspace]
+	if !ok {
+		return "", false
```
Comment (chris-olszewski) [inline cli/internal/lockfile/pnpm_lockfile.go:266]: I think we should probably panic in this scenario. If we're querying for dependencies of a non-existent workspace we're doing something wrong.

File: cli/internal/context/context.go (hunk 1 above)
Comment (gsoltis) [reply cli/internal/context/context.go]: Switched to `pkg.Dir` and `turbopath.AnchoredUnixPath`

File: cli/internal/lockfile/pnpm_lockfile.go (hunk 2 above)
Comment (gsoltis) [reply cli/internal/lockfile/pnpm_lockfile.go]: Added a panic here, are there other comparisons in here where we should panic?

File: cli/internal/lockfile/pnpm_lockfile.go [hunk 3]
```diff
@@ -255,30 +255,38 @@ func (p *PnpmLockfile) Patches() []turbopath.AnchoredUnixPath {
...
-				}
-				if resolvedVersion, ok := importer.OptionalDependencies[name]; ok {
-					return resolvedVersion, true
-				}
-
-				panic(fmt.Sprintf("Unable to find resolved version for %s@%s in %s", name, specifier, workspacePkg))
-			}
-		}
+	pnpmWorkspacePath := workspacePath.ToString()
+	if pnpmWorkspacePath == "" {
```
Comment (chris-olszewski) [inline cli/internal/lockfile/pnpm_lockfile.go:265]: Good call pushing this into the lockfile implementation

**Review by chris-olszewski — APPROVED** [review]
This looks good to me! Played around with it a bit and everything seemed in working order
