### PR TITLE
fix: sanitize logging prefix for GitLab groups

### LINKED ISSUE #10663: GitLab CI log grouping broken for packages in org (@organisation/pkg tasks)
### Verify canary release

- [x] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

-

### Which canary version will you have in your reproduction?

-

### Environment information

```block

```

### Expected behavior

Logs grouped by task in GitLab CI

### Actual behavior

Turbo does output the basic template correctly:
```
\e[0Ksection_start:1752345763:@organisation/package:test:tsc\r\
                                     e[0K@organisation/package:test:tsc@organisation/package:test:tsc: cache bypass, force executing 100a1b6fe0eec085
```

but GitLab CI [only allows `/a-zA-Z0-9._-/`](https://docs.gitlab.com/ci/jobs/job_logs/#custom-collapsible-sections) in section names (first `@organisation/package`). Section 'description' (part after `\e[0K`) is free to use any characters.

### To Reproduce

Name any package in the repository with `@` or `/` in it's name, as is usual for organisation/group scoped packages, for example `@organisation/package` and run turborepo in GitLab CI with `--log-order grouped` (should be default in CI according to docs).

### Additional context

Relevant changes introduced in #6188 and #8300.
Code which likely has the issue is [here](https://github.com/vercel/turborepo/blob/main/crates/turborepo-ci/src/vendors.rs#L298-L313), i.e. VendorBehavior for GitLab CI, as other CI providers may not have these limitations regarding section names

### PR DESCRIPTION
**Pull request by anthonyshew**
### Description

Closes #10663.

### Testing Instructions

Added a test to verify correctness.

Closes TURBO-4782

### CODE REVIEW

File: crates/turborepo-ci/src/vendors.rs [hunk 1]
```diff
@@ -299,16 +299,25 @@ pub(crate) fn get_vendors() -> &'static [Vendor] {
                         |group_name| {
                             Arc::new(move |start_time| {
                                 let timestamp = start_time.timestamp();
+                                // GitLab CI section names only allow /a-zA-Z0-9._-/ characters
+                                // Replace @ with 'at' and / with '-' for section identifier
+                                let sanitized_group_name =
+                                    group_name.replace('@', "at").replace('/', "-");
```
Comment (tknickman) [inline crates/turborepo-ci/src/vendors.rs]: Let's add a `-` suffix

File: crates/turborepo-ci/src/vendors.rs [hunk 2]
```diff
@@ -299,16 +299,25 @@ pub(crate) fn get_vendors() -> &'static [Vendor] {
...
                                 )
                             })
                         },
                         |group_name| {
                             Arc::new(move |end_time| {
                                 let timestamp = end_time.timestamp();
-                                format!("\\e[0Ksection_end:{timestamp}:{group_name}\\r\\e[0K")
+                                // Use the same sanitization for section end
+                                let sanitized_group_name =
+                                    group_name.replace('@', "at").replace('/', "-");
```
Comment (tknickman) [inline crates/turborepo-ci/src/vendors.rs]: Same

**Review by tknickman — APPROVED** [review]
