### PR TITLE
fix: output line with --output-logs=new-only should reflect actual behavior

### LINKED ISSUE #972: Logs shouldn't say "replaying output" when `--output-logs` suppresses the replayed output
### What version of Turborepo are you using?

1.1.10

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Very minor issue, but potentially confusing especially to newer users, and hopefully very easy to fix.

For default commands or commands with `--output-logs full`, the logs say things like:

```sh
@scope/package-name: cache hit, replaying output 1db9c7790acc4385
# replayed output from the last time this command was run is printed here
```

That's fine, it communicates that the command hasn't been re-run so the logs are repeats, not new content.

Trouble is, with `--output-logs new-only`, it displays the same message even though no output is replayed:

```sh
@scope/package-name: cache hit, replaying output 1db9c7790acc4385
@scope/another-package: cache hit, replaying output 790acc4381db975c
```

### Expected Behavior

If the output isn't replayed e.g. if `--output-logs new-only` is in effect, it'd make sense for the log message to reflect this, for example:

```sh
@scope/package-name: cache hit, no action 1db9c7790acc4385
@scope/another-package: cache hit, no action 790acc4381db975c
```

...or maybe:

```sh
@scope/package-name: cache hit, output suppressed 1db9c7790acc4385
@scope/another-package: cache hit, output suppressed 790acc4381db975c
```

### To Reproduce

In any repo with packages that haven't changed since the last build so will hit the cache, run:

```sh
turbo run build --output-logs new-only
```

### PR DESCRIPTION
**Pull request by chelkyl**
Closes #972 

image

### CODE REVIEW

**Comment by jaredpalmer** [comment]
@chelkyl awesome job with these PRs! Can you send me either a Twitter or Discord DM?

**Comment by chelkyl** [comment]
@jaredpalmer  Thanks for the notice, fixed!
Sent you a DM on Discord (from username z...).

File: cli/internal/run/run.go [hunk 1]
```diff
@@ -806,12 +806,10 @@ func replayLogs(logger hclog.Logger, prefixUi cli.Ui, runOptions *RunOptions, lo
 	}
 	defer f.Close()
 	if outputLogsMode != NoLogs {
-		scan := bufio.NewScanner(f)
 		if outputLogsMode == HashLogs {
-			//Writing to Stdout only the "cache hit, replaying output" line
-			scan.Scan()
-			prefixUi.Output(ui.StripAnsi(string(scan.Bytes())))
+			prefixUi.Output(fmt.Sprintf("%scache hit, suppressing output %s", logPrefix, ui.Dim(hash)))
```
Comment (gsoltis) [inline cli/internal/run/run.go:810]: This line seems a little weird: we're outputting from something called `prefixUi`, but we're also manually adding a prefix. 

I think we might want to refactor this a little to be less confusing. I think what's going on is the following:
 * the calling code has two `Ui` instances, one prefixed, one not
 * we're not actually passing in the prefixed one, because we expect the prefix to be in the logs already
  * we're then manually adding the prefix in the case where we are synthesizing a log line

Here's my proposal: 
 * check the `outputLogsMode` before calling `replayLogs`. 
 * If we're in 'NoLogs' mode, great, we're done
 * create a separate function to just output the cache hit for `HashLogs` mode. We're already not using the file contents in that case, so don't even open the file. Pass in the correct `Ui` instance that already has the prefix baked in (`targetUi`, I think). It doesn't even need to be in a goroutine, we could just call it directly. In fact, it might not even need to be function, it might even be just a single line
  * If we're in `FullLogs` mode, use the existing `replayLogs`
  * Remove the case for `NoLogs` in `replayLogs`

**Review by gsoltis — CHANGES_REQUESTED** [review]
Thanks for tackling this, I think the changes point to a need to do a little refactoring to make this a more straightforward change.

File: cli/internal/run/run.go (hunk 1 above)
Comment (jaredpalmer) [reply cli/internal/run/run.go:810]: sgtm

Comment (chelkyl) [reply cli/internal/run/run.go]: That refactor really cleans it up. Thanks for the suggestion!

File: cli/internal/run/run.go [hunk 2]
```diff
@@ -912,9 +904,16 @@ func (e *execContext) exec(pt *packageTask) error {
...
-			if e.rs.Opts.stream && fs.FileExists(filepath.Join(e.rs.Opts.cwd, logFileName)) {
-				e.logReplayWaitGroup.Add(1)
-				go replayLogs(targetLogger, e.ui, e.rs.Opts, logFileName, hash, &e.logReplayWaitGroup, false, e.rs.Opts.cacheHitLogsMode)
+			switch e.rs.Opts.cacheHitLogsMode {
+			case HashLogs:
+				targetUi.Output(fmt.Sprintf("cache hit, suppressing output %s", ui.Dim(hash)))
+			case FullLogs:
+				if e.rs.Opts.stream && fs.FileExists(filepath.Join(e.rs.Opts.cwd, logFileName)) {
+					e.logReplayWaitGroup.Add(1)
+					go replayLogs(targetLogger, e.ui, e.rs.Opts, logFileName, hash, &e.logReplayWaitGroup, false)
```
Comment (gsoltis) [inline cli/internal/run/run.go:913]: I realize it was here earlier, but let's get rid of the `false` for `silent` too. I think this is the only place where `replayLogs` is called.

File: cli/internal/run/run.go [hunk 3]
```diff
@@ -796,7 +796,7 @@ func (c *RunCommand) executeDryRun(engine *core.Scheduler, g *completeGraph, rs
 }
 
 // Replay logs will try to replay logs back to the stdout
-func replayLogs(logger hclog.Logger, prefixUi cli.Ui, runOptions *RunOptions, logFileName, hash string, wg *sync.WaitGroup, silent bool, outputLogsMode LogsMode) {
+func replayLogs(logger hclog.Logger, prefixUi cli.Ui, runOptions *RunOptions, logFileName, hash string, wg *sync.WaitGroup, silent bool) {
```
Comment (gsoltis) [inline cli/internal/run/run.go:799]: I think we can drop `silent`, it's only ever hard-coded to `false`. 

I think we also want to rename `prefixUi`, since it's not prefixed.

**Review by gsoltis — CHANGES_REQUESTED** [review]
Awesome, this is looking pretty good. Just a couple more minor suggestions to clean this up a little more.

File: cli/internal/run/run.go (hunk 3 above)
Comment (chelkyl) [reply cli/internal/run/run.go]: Sounds good, done!

File: cli/internal/run/run.go (hunk 2 above)
Comment (chelkyl) [reply cli/internal/run/run.go]: Done!

**Review by gsoltis — APPROVED** [review]
Nice work!
