### PR TITLE
fix handling of injected dependencies for pnpm prune

### LINKED ISSUE #2118: `turbo prune` produces a broken `pnpm-lock.yaml` lockfile with injected dependencies
### What version of Turborepo are you using?

1.5.4

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

`prune` command produces a broken `pnpm` lockfile if some dependency is marked as `injected`. If dependency is marked as `injected`, pnpm creates special lockfile entry with `file:` protocol. But these entries are missing in `turbo prune` result.

### Expected Behavior

The lock file should be valid.

### To Reproduce

`pnpm` version: v7.12.2

Clone the issue example repository and install dependencies via `pnpm`

```
$ git clone git@github.com:grigorii-zander/turborepo-pnpm-injected-bug.git
$ cd turborepo-pnpm-injected-bug
$ pnpm i
```

This repository contains one shared package:
- [internal-package](https://github.com/grigorii-zander/turborepo-pnpm-injected-bug/tree/main/packages/internal-package "internal-package")  just a dummy dependency
And two apps that depend on it:
- [with-regular-dep](https://github.com/grigorii-zander/turborepo-pnpm-injected-bug/tree/main/apps/with-regular-dep "with-regular-dep") with `packages/internal-package` added as a regular dependency
- [with-injected-dep](https://github.com/grigorii-zander/turborepo-pnpm-injected-bug/tree/main/apps/with-injected-dep "with-injected-dep") with `packages/internal-package` added as "injected" dependency. Here you can find the [injection directive](https://github.com/grigorii-zander/turborepo-pnpm-injected-bug/blob/main/apps/with-injected-dep/package.json#L7) for `@monorepo/internal-package`

Next, call the `prune` command on `with-regular-dep` app, and try to install the dependencies:
```
$ pnpm turbo prune --scope=with-regular-dep
$ cd out
$ pnpm i
```
The dependencies will be installed, and everything will work as expected.

Now try to do the same with `with-injected-dep` app:
```
$ cd ..
$ rm -fr ./out
$ pnpm turbo prune --scope=with-injected-dep
$ cd out
$ pnpm i
```

The installation will fail with the following error:
```
Lockfile is up to date, resolution step is skipped
 WARN  Broken lockfile: no entry for 'file:packages/internal-package' in pnpm-lock.yaml
 ERR_PNPM_ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  The lockfile is broken! Resolution step will be performed to fix it.
apps/with-injected-dep                   |  WARN  Moving date-fns that was installed by a different package manager to "node_modules/.ignored
apps/with-injected-dep                   |  WARN  Could not find preferred package file:packages/internal-package in lockfile
```

If we look at the original `./pnpm-lock.yaml` in the root of the repository, we can find the special `file:packages/internal-package` entry pointing to the "injected" package. But it's missing in `./out/pnpm-lock.yaml`

### PR DESCRIPTION
**Pull request by chris-olszewski**
Fixes #2118 

When a package is injected the resolutions will use the `file` protocol and it will appear in the packages section regardless of if it is a workspace package.

The fix here is to inspect the various importers for any injected packages and make sure to include any injected packages in the pruned lockfile.

### CODE REVIEW

**Review by mehulkar — COMMENTED** [review]
can we write a unit test?

File: cli/internal/lockfile/pnpm_lockfile.go [hunk 1]
```diff
@@ -186,6 +186,19 @@ func (p *PnpmLockfile) Subgraph(workspacePackages []turbopath.AnchoredSystemPath
 		return nil, err
 	}
 
+	for _, importer := range importers {
+		for dependency, meta := range importer.DependenciesMeta {
+			if meta.Injected {
+				resolution, ok := importer.Dependencies[dependency]
+				entry, entryOk := p.Packages[resolution]
+				if !ok || !entryOk {
+					return nil, fmt.Errorf("Unable to find package entry for %s in original lockfile", resolution)
```
Comment (grigorii-zander) [inline cli/internal/lockfile/pnpm_lockfile.go:195]: I think here you should print the `dependency` variable, otherwise it will print an empty string.

File: cli/internal/lockfile/pnpm_lockfile.go [hunk 2]
```diff
@@ -186,6 +186,19 @@ func (p *PnpmLockfile) Subgraph(workspacePackages []turbopath.AnchoredSystemPath
 		return nil, err
 	}
 
+	for _, importer := range importers {
+		for dependency, meta := range importer.DependenciesMeta {
+			if meta.Injected {
+				resolution, ok := importer.Dependencies[dependency]
```
Comment (grigorii-zander) [inline cli/internal/lockfile/pnpm_lockfile.go:192]: Here it's also necessary to lookup the `importer.DevDependencies`, because `injected` dependency cat also be a devDependency

**Review by NicholasLYang — APPROVED** [review]
I'm not super familiar with this area of the codebase but looks correct to me.
