### PR TITLE
Change Berry's `cacheKey` to be a string

### LINKED ISSUE #2101: Berry's `'yarn.lock'.__metadata.cacheKey` should be a string
### What version of Turborepo are you using?

1.5.4

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

Whenever `yarn.lock` contains a non-int `cacheKey:` field:
```yml
# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 6
  cacheKey: 8c0
```

Running `turbo run <ANYTHING>` results in the following error:
```
 ERROR  run failed: could not unmarshal lockfile: yaml: unmarshal errors:
  line 6: cannot unmarshal !!str `8c0` into int
```

### Expected Behavior

We should be able to parse `yarn.lock` with no issues.

### To Reproduce

https://github.com/amitdahan/turbo-yarn-berry-repro

Clone, `yarn`, `yarn build`
(Or see the included [failing GitHub Action](https://github.com/amitdahan/turbo-yarn-berry-repro/actions/runs/3143177017/jobs/5107613117#step:5:6))

Alternatively, in a Berry project, enable `compressionLevel: 0` and see `cacheKey` change into a non-int.

### PR DESCRIPTION
**Pull request by amitdahan**
# Summary

Closes #2101

### CODE REVIEW

File: cli/internal/lockfile/berry_lockfile.go [hunk 1]
```diff
@@ -216,7 +216,7 @@ func (l *BerryLockfile) Subgraph(workspacePackages []turbopath.AnchoredSystemPat
 	}
 
 	// berry only includes a cache key in the lockfile if there are entries with a checksum
-	cacheKey := -1
+	cacheKey := "-1"
```
Comment (chris-olszewski) [inline cli/internal/lockfile/berry_lockfile.go:219]: Now that we're using a string for `cacheKey` lets use `""` as the empty value.
```suggestion
	cacheKey := ""
```

**Review by chris-olszewski — CHANGES_REQUESTED** [review]
Thanks for fixing this! Just some small fixup needed before merging.

**Review by chris-olszewski — APPROVED** [review]

**Comment by amitdahan** [comment]
Thanks @chris-olszewski !
